# conda env create -f environment.yml
name: potassco_env
channels:
  - conda-forge
  - potassco
  - anaconda
dependencies:
  - clingo
  - clingraph
  - graphviz
  - pillow



# clingraph and dot dependencies graphviz